### ISSUE TITLE
How to get device_id and token

### ISSUE THREAD

**Issue by niuzhd** [jzhangdev/hass-352-skin-humidifier#1]
How to get device_id and token of the humidifier?
Thanks.

**Comment by jzhangdev** [comment]
Use the 352Life App and capture network requests, this is the only method available now.

Based on my own analysis of the application's network requests, it appears that the application is using Alibaba Cloud's IoT access service, which utilizes encrypted signature authentication. If one wishes to automate the process of obtaining device authentication information, I speculate that reverse engineering of the app would be necessary.

**Comment by niuzhd** [comment]
Thanks for reply.
Is it in log file named iotId,product key or target? Since I cannot find requests to api/device/info/ in the requests

**Comment by jzhangdev** [comment]
`https://app.352air.com/api/device/info/${device_id}`

`device_id` is in the request url params.
`token` is in the request headers `Authorization` field value, `Token ${token}`.

**Comment by jzhangdev** [comment]
`https://api.link.aliyun.com/uc/listBindingByAccount`

This request list all binding devices on your 352 account.

**Comment by niuzhd** [comment]
I have got that. Thank.you
