### ISSUE TITLE
请问目前是只支持展示状态，不支持控制设备么？

### ISSUE THREAD

**Issue by xzxxzx401** [jzhangdev/hass-352-skin-humidifier#3]
在HA里面修改状态比如开关加湿器、修改加湿器模式后，加湿器没有变化，数秒钟后状态会恢复成修改前的。

**Comment by jzhangdev** [comment]
Unfortunately control devices cannot be supported. Because the 352 manages the iOT hardware using Alibaba's cloud services, it requires the client to encrypt the request using a certificate, so this can't be done in the plugin right now.

**Comment by xzxxzx401** [comment]
Got it, Thanks

**Comment by xzxxzx401** [comment]
Got it, Thanks
